EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"

CHUNK_SIZE = 500
CHUNK_OVERLAP = 100

VECTORSTORE_DIR = "vectorstore"


GROQ_API_KEY="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"